


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "hypopg" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "index_advisor" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."create_public_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  -- Insert a profile for the newly created user.
  -- Use ON CONFLICT DO NOTHING to avoid duplicate errors.
  INSERT INTO public."Profile"(id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."create_public_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."CatalogItem" (
    "ItemType" smallint NOT NULL,
    "RiotItemID" integer NOT NULL,
    "Name" "text" NOT NULL,
    "SkinlineID" smallint,
    "ImageURL" "text",
    "CreatedAt" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
    "ChampionID" smallint,
    "ItemID" "uuid" NOT NULL,
    "ParentItemID" "uuid",
    "SortSection" smallint DEFAULT '0'::smallint NOT NULL
);


ALTER TABLE "public"."CatalogItem" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."CatalogSale" (
    "RiotItemID" integer NOT NULL,
    "SaleStartAt" timestamp with time zone NOT NULL,
    "SaleEndAt" timestamp with time zone NOT NULL,
    "NormalPrice" smallint NOT NULL,
    "SalePrice" smallint NOT NULL,
    "PercentOff" smallint NOT NULL,
    "IsActive" boolean NOT NULL,
    "ItemType" smallint NOT NULL,
    "Currency" "text" NOT NULL,
    "SaleID" "uuid" DEFAULT "gen_random_uuid"(),
    "Limited" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."CatalogSale" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Champion" (
    "id" integer NOT NULL,
    "Slug" "text" NOT NULL,
    "Name" "text" NOT NULL,
    "ImageURL" "text" NOT NULL
);


ALTER TABLE "public"."Champion" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ItemType" (
    "id" smallint NOT NULL,
    "Type" "text" NOT NULL
);


ALTER TABLE "public"."ItemType" OWNER TO "postgres";


ALTER TABLE "public"."ItemType" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ItemType_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."MythicSale" (
    "OfferID" "uuid" NOT NULL,
    "SaleStartAt" timestamp with time zone NOT NULL,
    "Price" smallint NOT NULL,
    "IsActive" boolean NOT NULL,
    "Currency" "text" NOT NULL,
    "Section" "text" NOT NULL,
    "PrimaryItemID" "uuid" NOT NULL,
    "IsBundle" boolean NOT NULL,
    "BundleType" "text",
    "IncludedItems" "text"[] NOT NULL,
    "SaleEndAt" timestamp with time zone NOT NULL,
    "SaleID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."MythicSale" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Profile" (
    "id" "uuid" NOT NULL,
    "email" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "EmailStatus" "text" DEFAULT 'active'::"text" NOT NULL,
    "EmailStatusUpdatedAt" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."Profile" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Skinline" (
    "id" smallint NOT NULL,
    "Name" "text",
    "UniverseID" smallint
);


ALTER TABLE "public"."Skinline" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Universe" (
    "id" smallint NOT NULL,
    "Name" "text" NOT NULL
);


ALTER TABLE "public"."Universe" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."WishlistEmailLog" (
    "UserID" "uuid" NOT NULL,
    "ItemID" "uuid" NOT NULL,
    "Status" "text" NOT NULL,
    "SentAt" timestamp with time zone,
    "SaleID" "uuid" NOT NULL,
    "SaleType" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "MythicSaleID" "uuid",
    "CatalogSaleID" "uuid"
);


ALTER TABLE "public"."WishlistEmailLog" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."WishlistItem" (
    "UserID" "uuid" NOT NULL,
    "ItemID" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."WishlistItem" OWNER TO "postgres";


ALTER TABLE ONLY "public"."CatalogItem"
    ADD CONSTRAINT "CatalogItem_pkey" PRIMARY KEY ("ItemID");



ALTER TABLE ONLY "public"."CatalogSale"
    ADD CONSTRAINT "CatalogSale_SaleID_key" UNIQUE ("SaleID");



ALTER TABLE ONLY "public"."CatalogSale"
    ADD CONSTRAINT "CatalogSale_pkey" PRIMARY KEY ("RiotItemID", "SaleStartAt", "SaleEndAt");



ALTER TABLE ONLY "public"."Champion"
    ADD CONSTRAINT "Champion_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."Champion"
    ADD CONSTRAINT "Champion_name_key" UNIQUE ("Name");



ALTER TABLE ONLY "public"."Champion"
    ADD CONSTRAINT "Champion_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Champion"
    ADD CONSTRAINT "Champion_slug_key" UNIQUE ("Slug");



ALTER TABLE ONLY "public"."ItemType"
    ADD CONSTRAINT "ItemType_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ItemType"
    ADD CONSTRAINT "ItemType_type_key" UNIQUE ("Type");



ALTER TABLE ONLY "public"."MythicSale"
    ADD CONSTRAINT "MythicSale_SaleID_key" UNIQUE ("SaleID");



ALTER TABLE ONLY "public"."MythicSale"
    ADD CONSTRAINT "MythicSale_pkey" PRIMARY KEY ("SaleStartAt", "Section", "PrimaryItemID", "SaleEndAt");



ALTER TABLE ONLY "public"."Profile"
    ADD CONSTRAINT "Profile_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Skinline"
    ADD CONSTRAINT "Skinline_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."Skinline"
    ADD CONSTRAINT "Skinline_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Universe"
    ADD CONSTRAINT "Universes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."WishlistEmailLog"
    ADD CONSTRAINT "WishlistEmailLog_pkey" PRIMARY KEY ("UserID", "ItemID", "SaleID");



ALTER TABLE ONLY "public"."WishlistItem"
    ADD CONSTRAINT "WishlistItem_pkey" PRIMARY KEY ("UserID", "ItemID");



ALTER TABLE ONLY "public"."CatalogItem"
    ADD CONSTRAINT "catalogitem_itemtype_riotitemid_unique" UNIQUE ("ItemType", "RiotItemID");



ALTER TABLE ONLY "public"."CatalogItem"
    ADD CONSTRAINT "CatalogItem_ChampionID_fkey" FOREIGN KEY ("ChampionID") REFERENCES "public"."Champion"("id");



ALTER TABLE ONLY "public"."CatalogItem"
    ADD CONSTRAINT "CatalogItem_ItemType_fkey" FOREIGN KEY ("ItemType") REFERENCES "public"."ItemType"("id");



ALTER TABLE ONLY "public"."CatalogItem"
    ADD CONSTRAINT "CatalogItem_ParentItemID_fkey" FOREIGN KEY ("ParentItemID") REFERENCES "public"."CatalogItem"("ItemID");



ALTER TABLE ONLY "public"."CatalogItem"
    ADD CONSTRAINT "CatalogItem_SkinlineID_fkey" FOREIGN KEY ("SkinlineID") REFERENCES "public"."Skinline"("id") ON DELETE SET DEFAULT;



ALTER TABLE ONLY "public"."CatalogSale"
    ADD CONSTRAINT "CatalogSale_ItemType_SkinID_fkey" FOREIGN KEY ("ItemType", "RiotItemID") REFERENCES "public"."CatalogItem"("ItemType", "RiotItemID");



ALTER TABLE ONLY "public"."MythicSale"
    ADD CONSTRAINT "MythicSale_PrimaryItemID_fkey" FOREIGN KEY ("PrimaryItemID") REFERENCES "public"."CatalogItem"("ItemID");



ALTER TABLE ONLY "public"."Profile"
    ADD CONSTRAINT "Profile_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Skinline"
    ADD CONSTRAINT "Skinline_UniverseID_fkey" FOREIGN KEY ("UniverseID") REFERENCES "public"."Universe"("id");



ALTER TABLE ONLY "public"."WishlistEmailLog"
    ADD CONSTRAINT "WishlistEmailLog_CatalogSaleID_fkey" FOREIGN KEY ("CatalogSaleID") REFERENCES "public"."CatalogSale"("SaleID");



ALTER TABLE ONLY "public"."WishlistEmailLog"
    ADD CONSTRAINT "WishlistEmailLog_ItemID_fkey" FOREIGN KEY ("ItemID") REFERENCES "public"."CatalogItem"("ItemID");



ALTER TABLE ONLY "public"."WishlistEmailLog"
    ADD CONSTRAINT "WishlistEmailLog_MythicSaleID_fkey" FOREIGN KEY ("MythicSaleID") REFERENCES "public"."MythicSale"("SaleID");



ALTER TABLE ONLY "public"."WishlistEmailLog"
    ADD CONSTRAINT "WishlistEmailLog_UserID_fkey" FOREIGN KEY ("UserID") REFERENCES "public"."Profile"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."WishlistItem"
    ADD CONSTRAINT "WishlistItem_ItemID_fkey" FOREIGN KEY ("ItemID") REFERENCES "public"."CatalogItem"("ItemID");



ALTER TABLE ONLY "public"."WishlistItem"
    ADD CONSTRAINT "WishlistItem_UserID_fkey" FOREIGN KEY ("UserID") REFERENCES "public"."Profile"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."CatalogItem" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."CatalogSale" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Champion" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable read access for all users" ON "public"."CatalogItem" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."CatalogSale" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."Champion" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."ItemType" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."MythicSale" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."Skinline" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."Universe" FOR SELECT USING (true);



ALTER TABLE "public"."ItemType" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."MythicSale" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Profile" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Skinline" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Universe" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Users can only delete their own rows" ON "public"."WishlistItem" FOR DELETE USING (("auth"."uid"() = "UserID"));



CREATE POLICY "Users can only insert their own, up to 25" ON "public"."WishlistItem" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"() = "UserID") AND (( SELECT "count"(*) AS "count"
   FROM "public"."WishlistItem" "wi"
  WHERE ("wi"."UserID" = "auth"."uid"())) < 50)));



CREATE POLICY "Users can only update their own rows" ON "public"."WishlistItem" FOR UPDATE USING (("auth"."uid"() = "UserID")) WITH CHECK (("auth"."uid"() = "UserID"));



CREATE POLICY "Users can only view their own table" ON "public"."WishlistItem" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "UserID"));



ALTER TABLE "public"."WishlistEmailLog" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."WishlistItem" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


























































































































































































REVOKE ALL ON FUNCTION "public"."create_public_user"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."create_public_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."create_public_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_public_user"() TO "service_role";
























GRANT ALL ON TABLE "public"."CatalogItem" TO "anon";
GRANT ALL ON TABLE "public"."CatalogItem" TO "authenticated";
GRANT ALL ON TABLE "public"."CatalogItem" TO "service_role";



GRANT ALL ON TABLE "public"."CatalogSale" TO "anon";
GRANT ALL ON TABLE "public"."CatalogSale" TO "authenticated";
GRANT ALL ON TABLE "public"."CatalogSale" TO "service_role";



GRANT ALL ON TABLE "public"."Champion" TO "anon";
GRANT ALL ON TABLE "public"."Champion" TO "authenticated";
GRANT ALL ON TABLE "public"."Champion" TO "service_role";



GRANT ALL ON TABLE "public"."ItemType" TO "anon";
GRANT ALL ON TABLE "public"."ItemType" TO "authenticated";
GRANT ALL ON TABLE "public"."ItemType" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ItemType_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ItemType_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ItemType_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."MythicSale" TO "anon";
GRANT ALL ON TABLE "public"."MythicSale" TO "authenticated";
GRANT ALL ON TABLE "public"."MythicSale" TO "service_role";



GRANT ALL ON TABLE "public"."Profile" TO "anon";
GRANT ALL ON TABLE "public"."Profile" TO "authenticated";
GRANT ALL ON TABLE "public"."Profile" TO "service_role";



GRANT ALL ON TABLE "public"."Skinline" TO "anon";
GRANT ALL ON TABLE "public"."Skinline" TO "authenticated";
GRANT ALL ON TABLE "public"."Skinline" TO "service_role";



GRANT ALL ON TABLE "public"."Universe" TO "anon";
GRANT ALL ON TABLE "public"."Universe" TO "authenticated";
GRANT ALL ON TABLE "public"."Universe" TO "service_role";



GRANT ALL ON TABLE "public"."WishlistEmailLog" TO "anon";
GRANT ALL ON TABLE "public"."WishlistEmailLog" TO "authenticated";
GRANT ALL ON TABLE "public"."WishlistEmailLog" TO "service_role";



GRANT ALL ON TABLE "public"."WishlistItem" TO "anon";
GRANT ALL ON TABLE "public"."WishlistItem" TO "authenticated";
GRANT ALL ON TABLE "public"."WishlistItem" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

CREATE TRIGGER create_public_user_on_signup AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_public_user();


